name: Brian Mikulencak Business Transactions and Tax Attorney
h1: <span itemprop="name">Brian Mikulencak</span><br /><span itemprop="name">Business Transactions and Tax Attorney</span>
tagline: Counseling for start-ups, growth companies, and entrepreneurs
markdown: redcarpet
pygments: true
