name: Brian Mikulencak Business Transactions and Tax Attorney
header: <div id="top">
          <div class="row">
            <div class="large-12 columns">
              <header itemscope itemtype="http://schema.org/Organization">
                <h1 class="site-name"><a class="title-link" href="/index.html"><span itemprop="name">Brian Mikulencak</span><br /><span itemprop="name">Business Transactions and Tax Attorney</span></a></h1>
                <p class="tagline" itemprop="description">Counseling for start-ups, growth companies, and entrepreneurs</p>
              </header>
            </div>
          </div>
        </div>
footer: <div id="bottom">
          <div class="row">
            <div class="large-12 columns">
              <footer>
                <p>&copy; 2014 Brian Mikulencak, 1800 Romford Dr. Austin, Tx 78704, All rights reserved.</p>
              </footer>
            </div>
          </div>
        </div>
markdown: redcarpet
pygments: true
